#--------------------------------------------------
# Version:
# NOTE: UPDATE THIS TO UPDATE ASSEMBLY AND NUGET 
# VERSIONS!!!!!!!!
#--------------------------------------------------
version: '1.1.{build}'

#--------------------------------------------------
# Build worker image (VM template)
# TODO: Move everything to VS.NET 2017
#--------------------------------------------------
image: Visual Studio 2015

#--------------------------------------------------
# Environment
#--------------------------------------------------
environment:
  github_personal_access_token:
    secure: PNVFwcCuNr+X7SffsiwiVsa/JzVyZqwNJUbeve+Or/EjOwZxbd1CUC0K/5az9jsT
  git_tag_version: 'v{version}'

#--------------------------------------------------
# Branch whitelist
#--------------------------------------------------
branches:
  # Whitelist
  only:
    - master

# Do not build on tags, since we auto-commit tags.
skip_tags: true

#--------------------------------------------------
# After cloning repository
#--------------------------------------------------
install:
  - git submodule init
  - git submodule update

#--------------------------------------------------
# Build configuration
#--------------------------------------------------
configuration: Release

#--------------------------------------------------
# Assembly version patching
#-------------------------------------------------- 
assembly_info:
  patch: true
  file: '**\GlobalAssemblyInfo.cs'
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

#--------------------------------------------------
# Build hooks - before
#--------------------------------------------------
before_build:
  - nuget restore -verbosity detailed
  
#--------------------------------------------------
# Build hooks - after
#--------------------------------------------------
after_build:
   - nuget pack src\%APPVEYOR_PROJECT_NAME%\%APPVEYOR_PROJECT_NAME%.csproj -verbosity detailed
 
#--------------------------------------------------
# Build hooks - on_success
#
# Tags the repository in GitHub with the release version.
#--------------------------------------------------
on_success:
  - git config --global credential.helper store
  - ps: Add-Content "$env:USERPROFILE\.git-credentials" "https://$($env:github_personal_access_token):x-oauth-basic@github.com`n"
  - git config --global user.email "admin@oneframelink.com"
  - git config --global user.name "One Frame Link"
  - git tag "%git_tag_version%"
  - git push origin "%git_tag_version%"
 
#--------------------------------------------------
# NuGet config
#--------------------------------------------------
nuget:
  # disable publishing of .nupkg artifacts to
  # account/project feeds for pull request builds
  disable_publish_on_pr: true
  
#--------------------------------------------------
# Artifact configuration
#--------------------------------------------------
artifacts:  
  - path: '**\*.nupkg'
    name: NuGet

#--------------------------------------------------
# Deploy NuGet
#--------------------------------------------------
deploy:
  provider: NuGet
  api_key:
    secure: AhNvfOiNoCPXb1PnRG18sOfxSmsS+q4iNJ30PsuABsau99QGZ46C4nhSRSoUZehg
  artifact: /{APPVEYOR_PROJECT_NAME}\.{version}\.nupkg/
  
#--------------------------------------------------
# Notifications
#--------------------------------------------------
notifications:
  - provider: Slack
    incoming_webhook:
      secure: Y4pw1Q3aqUk/4aVYHN5R3u5Zca5ijyVi6tRAVahXhlFXFCZTwpJLrEwHsRGoqQGIkUUpAOvlOpVRNoXBKJhfwkHybRotzfi7SbbB8Rb+67I= 
